name: Bug Report
description: Create a report to fix a problem
title: "bug: "
labels:
  - ":bug: bug"

body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
